export const items = {
    1: 'MASTER BALL',
    2: 'ULTRA BALL',
    3: 'GREAT BALL',
    4: 'POKé BALL',
    17: 'POTION',
    18: 'ANTIDOTE',
    19: 'BURN HEAL',
    20: 'ICE HEAL',
    21: 'AWAKENING',
    22: 'PARLYZ HEAL',
    23: 'FULL RESTORE',
    24: 'MAX POTION',
    25: 'HYPER POTION',
    26: 'SUPER POTION',
    27: 'FULL HEAL',
    28: 'REVIVE',
    76: 'SUPER REPEL',
    77: 'MAX REPEL',
    78: 'ESCAPE ROPE',
    79: 'REPEL',
};
